### ISSUE TITLE
ReportCLI not functioning

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/peptide-shaker-2.0-issue-tracker#54] opened 2020-04-18 02:12 UTC
[PeptideShaker.log](https://github.com/compomics/peptide-shaker-2.0-issue-tracker/files/4495872/PeptideShaker.log)

My commands:
java -cp PeptideShaker-2.0.0-beta.jar eu.isas.peptideshaker.cmd.ReportCLI -in /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/ps_out/output1.cpsx -out_reports /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/output -reports 0, 1, 3, 4, 6, 9, 11 -report_prefix "RPP2_" -gzip 0 > out7.log &

**Comment by CarlaCristinaUranga** [comment] 2020-04-18 03:28
I tried re-running PeptideShaker to produce a .zip output file and I got this error:

Fri Apr 17 20:23:56 PDT 2020 Unzipping output3.zip. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Fri Apr 17 20:25:36 PDT 2020 An error occurred while loading the spectrum file(s).
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/resources/matches/.nfs0000000325693c8d005e8200 could not be deleted!
 
My commands were:
java -cp PeptideShaker-2.0.0-beta.jar eu.isas.peptideshaker.cmd.ReportCLI -in /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/ps_out/output3.zip -out_reports /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/output -reports 0, 1, 3, 4, 6, 9, 11 -report_prefix "RPP2_" -gzip 0 > out7.log &

**Comment by hbarsnes** [comment] 2020-04-18 09:27
Due to the known issue with opening saved projects (https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues/47) you cannot yet use the ReportCLI command line in the beta version. The trick is therefore to add the -out_reports and -reports options directly to the PeptideShakerCLI command line. This is also generally faster, given that you do not have to save and reopen the project.

**Comment by CarlaCristinaUranga** [comment] 2020-04-18 15:41
Would syntax like this work?:
java -cp PeptideShaker-2.0.0-beta.jar
eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference salivary_metaproteome
-fasta_file
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta
-identification_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output2/CU_2RPP_02.msgf.mzid
-spectrum_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/CU_2RPP_02.mgf
-out_reports
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports
-reports 0, 1, 3, 4, 6, 9, 11 -threads 10 > out15.log &

Best,
Carla

**Comment by hbarsnes** [comment] 2020-04-18 19:42
Almost. You just have to change -reports 0, 1, 3, 4, 6, 9, 11 into -reports "0, 1, 3, 4, 6, 9, 11"

**Comment by CarlaCristinaUranga** [comment] 2020-04-19 01:00
Hmmm still no cigar for me. I tried with embedding the entire Report CLI java command with Peptide Shaker and with only including the commands from Report CLI:

java -cp PeptideShaker-2.0.0-beta.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference salivary_metaproteome -fasta_file /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta -identification_files /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output2/CU_2RPP_02.msgf.mzid -spectrum_files /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/CU_2RPP_02.mgf -out /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx & java -cp PeptideShaker-2.0.0-beta.jar eu.isas.peptideshaker.cmd.ReportCLI -in /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx -out_reports /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports -reports "0, 1, 3, 4, 6, 9, 11"  > outPS.log &



java -cp PeptideShaker-2.0.0-beta.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference salivary_metaproteome -fasta_file /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta -identification_files /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output2/CU_2RPP_02.msgf.mzid -spectrum_files /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/CU_2RPP_02.mgf -out /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx -in /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx -out_reports /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports -reports "0, 1, 3, 4, 6, 9, 11" > outPS.log &

**Comment by hbarsnes** [comment] 2020-04-19 10:07
When using the ReportCLI options via the PeptideShakerCLI you should not include -in /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx

**Comment by CarlaCristinaUranga** [comment] 2020-04-19 14:48
Ok I still can't get it to work, I can't give up. Proteomics is too
interesting! Here is what I tried, I put each command on a separate line so
it is easier for you to read. Thank you Harald!

Try#1 with java called twice:

java -cp PeptideShaker-2.0.0-beta.jar
eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference salivary_metaproteome
-fasta_file
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta
-identification_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output/CU_2RPP_02.msgf.mzid
-spectrum_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/CU_2RPP_02.mgf
-id_params
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/saliva.par
-out
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx
&
java -cp PeptideShaker-2.0.0-beta.jar eu.isas.peptideshaker.cmd.ReportCLI
-out_reports
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports
-reports "0, 1, 3, 4, 6, 9, 11"  > outPS.log &

Try#2 with only calling PeptideShaker:

java -cp PeptideShaker-2.0.0-beta.jar
eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference salivary_metaproteome
-fasta_file
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta
-identification_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output/CU_2RPP_02.msgf.mzid
-spectrum_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/CU_2RPP_02.mgf
-id_params
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/saliva.par
-out
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx
-out_reports
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports
-reports "0, 1, 3, 4, 6, 9, 11"  > outPS.log &

**Comment by hbarsnes** [comment] 2020-04-19 16:01
> Try#1 with java called twice

This will not work until we've fixed the issue with reopening saved PeptideShaker projects. (And would requrie that you add the -in option with the PeptideShaker project to the second command line.)

> Try#2 with only calling PeptideShaker

This one looks more promissing. So what kind of errors do you get when trying to run it?

**Comment by CarlaCristinaUranga** [comment] 2020-04-19 16:54
This is the error I get:

[curanga@bigmem-11 PeptideShaker-2.0.0-beta]$ Error: A JNI error has
occurred, please check your installation and try again

Exception in thread "main" java.lang.NoClassDefFoundError:
com/compomics/util/experiment/personalization/UrParameter

at java.lang.Class.getDeclaredMethods0(Native Method)

at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)

at java.lang.Class.privateGetMethodRecursive(Class.java:3048)

at java.lang.Class.getMethod0(Class.java:3018)

at java.lang.Class.getMethod(Class.java:1784)

at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)

at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)

Caused by: java.lang.ClassNotFoundException:
com.compomics.util.experiment.personalization.UrParameter

at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)

at java.lang.ClassLoader.loadClass(ClassLoader.java:3

**Comment by hbarsnes** [comment] 2020-04-19 17:12
And what is the command line you are trying to run when getting this error?

And which Java version are you using? You can find out by running java -version

**Comment by CarlaCristinaUranga** [comment] 2020-04-19 17:20
*Thank you for your patience!*


*Java -version:*


[curanga@bigmem-11 PeptideShaker-2.0.0-beta]$ java -version

openjdk version "1.8.0_232"

OpenJDK Runtime Environment (build 1.8.0_232-b09)

OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

[curanga@bigmem-11 PeptideShaker-2.0.0-beta]$


*Commands (on separate lines for ease of reading):*


java -cp PeptideShaker-2.0.0-beta.jar
eu.isas.peptideshaker.cmd.PeptideShakerCLI

-reference salivary_metaproteome -fasta_file
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta

-identification_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output/CU_2RPP_02.msgf.mzid

-spectrum_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/CU_2RPP_02.mgf

-id_params
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/saliva.par

-out
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx

-out_reports
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/PeptideShaker-2.0.0-beta/reports2

-reports "0, 1, 3, 4, 6, 9, 11"  > outPS.log &

**Comment by hbarsnes** [comment] 2020-04-19 18:39
If I replace your paths with my own I'm able to run your PeptideShakerCLI without any issues.

You may try updating your Java version?

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 16:06
*Hi so I updated my java version to version 14:*

[curanga@lserver1 PeptideShaker-2.0.0-beta]$ java -version

openjdk version "14.0.1" 2020-04-14

OpenJDK Runtime Environment (build 14.0.1+7)

OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

[curanga@lserver1 PeptideShaker-2.0.0-beta]$


*I did verify that the installation was correct by running SearchGUI and
this was successful using SearchGUI. However, with PeptideShaker it is not
working with** the following command (same as before that worked with you):*

java -cp PeptideShaker-2.0.0-beta.jar
eu.isas.peptideshaker.cmd.PeptideShakerCLI

-reference salivary_metaproteome

-fasta_file
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/SearchGUI-4.0.0-beta/HOMDdb.fasta

-identification_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/SearchGUI-4.0.0-beta/mgf/RPP_02/CU_2RPP_02.msgf.mzid

-spectrum_files
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/SearchGUI-4.0.0-beta/mgf/CU_2RPP_02.mgf

-id_params
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/SearchGUI-4.0.0-beta/saliva.par

-out
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideShaker-2.0.0-beta/reports/rpp_02.cpsx

-out_reports
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideShaker-2.0.0-beta/reports2

-reports "0, 1, 3, 4, 6, 9, 11"  > outPS.log &


*And now I get the following error:*

[curanga@lserver1 PeptideShaker-2.0.0-beta]$ Error: Unable to initialize
main class eu.isas.peptideshaker.cmd.PeptideShakerCLI

Caused by: java.lang.NoClassDefFoundError:
com/compomics/util/experiment/personalization/UrParameter


*Thanks!*

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 16:41
Maybe if you could let me know what version of Java you are using and I
will switch to your version. Thanks again Harald!

Best wishes,
Carla

**Comment by hbarsnes** [comment] 2020-04-20 17:16
> Maybe if you could let me know what version of Java you are using and I will switch to your version.

I tested with java version "1.8.0_241" yesterday. Oracle not OpenJDK though. But should not matter.

Maybe there is something wrong with your PeptideShaker build. Try this updated beta version: http://vedlegg.uib.no/?id=fc7352ef0a49748af9fb3a4a2dae1c04.

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 18:08
*Ok the program got a little further but then reported this error:*
Mon Apr 20 10:50:39 PDT 2020: PeptideShaker version 2.0.0-beta.
Memory given to the Java virtual machine: 32178700288.
Total amount of memory in the Java virtual machine: 2155872256.
Free memory: 2137188352.
Java version: 14.0.1.
java.lang.NullPointerException
at
com.compomics.util.experiment.identification.peptide_shaker.PSModificationScores.changeRepresentativeSite(PSModificationScores.java:329)
at
eu.isas.peptideshaker.ptm.ModificationLocalizationScorer.peptideInference(ModificationLocalizationScorer.java:2298)
at eu.isas.peptideshaker.PeptideShaker.createProject(PeptideShaker.java:432)
at
eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:1100)
at
eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:222)
at
eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1304)

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 18:12
*The output log file says this (just the end part)*
Mon Apr 20 10:58:34 PDT 2020 Importing PSMs from CU_2RPP_02.msgf.mzid
 60% 70% 80% 90% 100% 110% 120% 130% 140% 150%
Mon Apr 20 11:00:10 PDT 2020 File import completed. 101093 first hits
imported (848258 total) from 109497 spectra.
Mon Apr 20 11:00:10 PDT 2020 [101093 first hits passed the initial
filtering]
Mon Apr 20 11:00:11 PDT 2020 Computing assumptions probabilities.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Apr 20 11:00:12 PDT 2020 Saving assumptions probabilities, selecting
best match, scoring modification localization.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 20 11:01:11 PDT 2020 Computing PSM probabilities.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 20 11:01:12 PDT 2020 Resolving peptide inference issues.
Mon Apr 20 11:01:12 PDT 2020 Peptide Inference. Please Wait...
10% 20% 30% 40% 50% 60%
Mon Apr 20 11:01:29 PDT 2020 An error occurred while creating the
PeptideShaker project. Please see the PeptideShaker log file:
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideShaker-2.0.0-beta/resources/PeptideShaker.log

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 19:17
*I also get this upon submitting the command on the terminal (ssh):*


WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
(file:/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideShaker-2.0.0-beta/lib/gson-2.4.jar)
to field java.awt.Color.value

WARNING: Please consider reporting this to the maintainers of
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory

WARNING: Use --illegal-access=warn to enable warnings of further illegal
reflective access operations

WARNING: All illegal access operations will be denied in a future release

**Comment by hbarsnes** [comment] 2020-04-20 19:29
Ok, so at least you now get it to run. :)

Can you share the data so that I can try to reproduce the issue on my end?

The illegal reflective access warning you can ignore.

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 19:48
Ok do you have a private email to share the data via the google drive?

Best,
Carla

**Comment by hbarsnes** [comment] 2020-04-20 19:57
Hi Carla,

You can send the link to me at harald.barsnes@gmail.com.

Best regards,
Harald

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 19:59
ok I sent you the link to the data

**Comment by hbarsnes** [comment] 2020-04-20 20:06
> ok I sent you the link to the data

As far as I can tell you shared a folder that only contains four mgf files? Or are you still uploading data to the shared folder? I need all of the files you use as part of your command line.

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 20:53
ok it will take a bit to download the .zip file from Search GUI. Do you need the database as well? It is super large!

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 21:00
I am looking for a way to transfer these massive files to you from the server...

**Comment by hbarsnes** [comment] 2020-04-20 21:01
> ok it will take a bit to download the .zip file from Search GUI. Do you need the database as well? It is super large!

Yes, I will need the database as well, but if it is very large I probably won't be able to open the project on my laptop anyway. Which is the only think I have access to at the moment. How large is super large btw?

So perhaps we should look into other options. For example, can you send me only your parameter file?

**Comment by CarlaCristinaUranga** [comment] 2020-04-20 21:39
I zipped it up and it is at 750 Mb. Unzipped it is 1.4 Gb! That is why a
server is absolutely required for this. A laptop is not able to do this. I
have attached the parameter file to this email in case you can use it.
Thank you! I hope we are able to solve this. You will go on the publication
as a co-author if we are able to get this to work.

Best wishes,
Carla

**Comment by hbarsnes** [comment] 2020-04-21 00:56
> I zipped it up and it is at 750 Mb. Unzipped it is 1.4 Gb!

Can I ask what kind of sequences the database contains given that it is so large?

> I have attached the parameter file to this email in case you can use it.

I'm afraid that does not work. You have to upload the file via the issue tracker or send it to me directly.

**Comment by CarlaCristinaUranga** [comment] 2020-04-21 01:59
Hi Here is the uploaded .par file.


[saliva.par.txt](https://github.com/compomics/peptide-shaker-2.0-issue-tracker/files/4507243/saliva.par.txt)

**Comment by CarlaCristinaUranga** [comment] 2020-04-21 03:28
Yes the database is just the HOMD proteome database available from www.homd.org

**Comment by hbarsnes** [comment] 2020-04-21 08:54
Perhaps you can try turning of the PTM localization scoring? This should be fine given that you are not searching for biologically interesting PTMs anyway, such as phosphorylations.

To turn of the PTM localization scoring do the following: open your parameter file (preferably via the GUI), click the Show Advanced Settings, open the PTM Localization settings, set the Probalistic Score to None and Confident Sites (under Site Alignment) to No. Then try running the command line again.

**Comment by CarlaCristinaUranga** [comment] 2020-04-21 20:49
*Hi I tried switching the parameter files in peptide shaker but got the
same error. I am re-running SearchGUI from the beginning with the new
settings to see if this helps:*

*Peptide Shaker log:*
Tue Apr 21 12:57:26 PDT 2020: PeptideShaker version 2.0.0-beta.
Memory given to the Java virtual machine: 32178700288.
Total amount of memory in the Java virtual machine: 2155872256.
Free memory: 2137188352.
Java version: 14.0.1.
java.lang.NullPointerException
at
com.compomics.util.experiment.identification.peptide_shaker.PSModificationScores.changeRepresentativeSite(PSModificationScores.java:329)
at
eu.isas.peptideshaker.ptm.ModificationLocalizationScorer.peptideInference(ModificationLocalizationScorer.java:2298)
at eu.isas.peptideshaker.PeptideShaker.createProject(PeptideShaker.java:432)
at
eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:1100)
at
eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:222)
at
eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1304)

*Output log:*
Tue Apr 21 12:57:30 PDT 2020 Importing sequences from HOMDdb.fasta.
Tue Apr 21 12:57:51 PDT 2020 Importing gene mappings.
Tue Apr 21 12:59:07 PDT 2020 Establishing local database connection.
Tue Apr 21 12:59:07 PDT 2020 Reading identification files.
Tue Apr 21 12:59:07 PDT 2020 Parsing CU_2CPP_01.msgf.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tue Apr 21 12:59:53 PDT 2020 Checking spectra for CU_2CPP_01.msgf.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tue Apr 21 12:59:53 PDT 2020 Importing PSMs from CU_2CPP_01.msgf.mzid
 60% 70% 80% 90% 100% 110% 120% 130% 140% 150%
Tue Apr 21 13:01:43 PDT 2020 File import completed. 94740 first hits
imported (799041 total) from 103924 spectra.
Tue Apr 21 13:01:43 PDT 2020 [94740 first hits passed the initial filtering]
Tue Apr 21 13:01:45 PDT 2020 Computing assumptions probabilities.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tue Apr 21 13:01:46 PDT 2020 Saving assumptions probabilities, selecting
best match, scoring modification localization.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Tue Apr 21 13:02:04 PDT 2020 Computing PSM probabilities.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Tue Apr 21 13:02:05 PDT 2020 Resolving peptide inference issues.
Tue Apr 21 13:02:05 PDT 2020 Peptide Inference. Please Wait...
10% 20% 30% 40% 50% 60% 70%
Tue Apr 21 13:02:14 PDT 2020 An error occurred while creating the
PeptideShaker project. Please see the PeptideShaker log file:
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideShaker-2.0.0-beta/resources/PeptideShaker.log

**Comment by CarlaCristinaUranga** [comment] 2020-04-21 22:11
I am thinking that this is happening because we are using a non-Uniprot
database?

Carla

**Comment by hbarsnes** [comment] 2020-04-21 23:01
> I tried switching the parameter files in peptide shaker but got the same error.

Are you sure this is with the new parameter file with the PTM localization scoring turned off? Because if Confident Sites (under Site Alignment) is set to No, the part of the code giving the error is not used.

> I am thinking that this is happening because we are using a non-Uniprot database?

No, I don't think so. The errors you are currently getting are all about PTM localization scoring. Which for some reason seems to happen more often when using MS-GF+ btw. So unless you have particular reasons for using MS-GF+ you may consider changing the search engine? Although turning the PTM localization scoring off should solve the issue.

**Comment by CarlaCristinaUranga** [comment] 2020-04-21 23:11
I swear I changed it, but if I got something wrong I attached the current
.par file. I am trying with a uniprot database, but thanks for the tip on
using another algorithm besides MSGF. Which one do you like that does not
have this problem?

Best wishes,
Carla

**Comment by hbarsnes** [comment] 2020-04-21 23:30
> I swear I changed it, but if I got something wrong I attached the current .par file

The parameter file you shared seems to be ok. Are you sure this is the one you are using on the command line?

> thanks for the tip on using another algorithm besides MSGF. Which one do you like that does not have this problem?

Most of them should be fine. You can for example try X! Tandem.

**Comment by CarlaCristinaUranga** [comment] 2020-04-22 00:14
Harald I am obsessing over syntax! Hahaha I can't afford to make syntax
errors. SO I am now running SearchGUI with X! Tandem and am looking forward
to the results :). I will let you know! Have a great day and I hope you are
staying well during this coronavirus situation. Over here in the US we are
like the third world in our political response to this pandemic. It is
truly shameful how intellectually low things have gotten in the US.

Best wishes,
Carla

**Comment by CarlaCristinaUranga** [comment] 2020-04-23 17:49
*Hi Harald so X! Tandem is definitely working. It is MSGF that is not
working, so you were right about this being an issue with MSGF. I have read
that MSGF is great because you get more hits. This is why I have been using
it, it is too bad that there is this bug, hopefully you guys can fix it in
future versions. I am currently using all algorithms except Tide, MSGF and
Andromeda to see if I can get more identifications. Again thanks for your
help and I will definitely follow any updates you guys put out there!*

*Best wishes,*
*Carla*

**Comment by hbarsnes** [comment] 2020-04-23 21:58
Hi Carla,

Great! Good luck with the interpretation of the data!

I will then close this issue (as it was really about getting the ReportCLI to work), but do not hesitate to open a new one if you come across other problems.

Best regards,
Harald

**Closed as completed by hbarsnes** 2020-04-23 21:58 UTC
Labels: help wanted
